title: Naufal - Resume
profile_img: /assets/img/profile.jpg
icon_img: /assets/img/github-original.webp

name: "Muhammad Naufal Hanif"
job: "DevOps Engineer | Axway API Developer | System Engineer"

phone_number: "+6282117469247"
address: "Bekasi, Indonesia"
email: naufalmng@gmail.com
linkedin_username: mnaufalhanif
github_username: naufalmng
instagram_username: naufalh.apk
twitter_username: naufaltechhub
facebook_username: muhammad.naufal.hanif
youtube_username: NaufalTechHub
blog_url: naufaltechhub.medium.com

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /resume
baseurl:

exclude:
  - _posts/
  - resources/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag